# Copyright 2010 - 2013, Qualcomm Innovation Center, Inc.
# 
#    Licensed under the Apache License, Version 2.0 (the "License");
#    you may not use this file except in compliance with the License.
#    You may obtain a copy of the License at
# 
#        http://www.apache.org/licenses/LICENSE-2.0
# 
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS,
#    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#    See the License for the specific language governing permissions and
#    limitations under the License.
# 

Import('env')

# JNI library sources
srcs = ['alljoyn_java.cc']

#if env['OS'] == 'android':
#	srcs += ['P2pHelperService.cc']

objs = env.SharedObject(srcs)

# JNI library
bdenv = env.Clone()
if bdenv['BD'] == 'off':
    # The JNI code must link in the bundled daemon even if BD is set to 'off'
    bdenv.Prepend(LIBS = ['ajdaemon'])
    bdenv.Prepend(LIBS = env['bdobj'])


liballjoyn_java = bdenv.SharedLibrary('alljoyn_java', objs)

Return('liballjoyn_java')
