# Copyright 2010 - 2011, Qualcomm Innovation Center, Inc.
# 
#    Licensed under the Apache License, Version 2.0 (the "License");
#    you may not use this file except in compliance with the License.
#    You may obtain a copy of the License at
# 
#        http://www.apache.org/licenses/LICENSE-2.0
# 
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS,
#    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#    See the License for the specific language governing permissions and
#    limitations under the License.
# 

import os
import string
Import('env')

# AllJoyn Java binding
test_classes = env.Java('$CLASSDIR', '.', JAVACLASSPATH=os.pathsep.join(
        [env.subst('$JAVACLASSPATH'), env.GetBuildPath(env.subst('$JARDIR/alljoyn.jar'))]))
env.Jar('$JARDIR/alljoyn_test.jar', test_classes)
env.Requires(test_classes, '$JARDIR/alljoyn.jar')
