# Copyright 2011, Qualcomm Innovation Center, Inc.
# 
#    Licensed under the Apache License, Version 2.0 (the "License");
#    you may not use this file except in compliance with the License.
#    You may obtain a copy of the License at
# 
#        http://www.apache.org/licenses/LICENSE-2.0
# 
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS,
#    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#    See the License for the specific language governing permissions and
#    limitations under the License.
# 

Import('env')

env.SConscript('JavaSDKDocMethodsClient/SConscript')
env.SConscript('JavaSDKDocMethodsService/SConscript')
env.SConscript('JavaSDKDocPropertiesClient/SConscript')
env.SConscript('JavaSDKDocPropertiesService/SConscript')
env.SConscript('JavaSDKDocSecurityLogonClient/SConscript')
env.SConscript('JavaSDKDocSecurityLogonService/SConscript')
env.SConscript('JavaSDKDocSecurityRsaClient/SConscript')
env.SConscript('JavaSDKDocSecurityRsaClient2/SConscript')
env.SConscript('JavaSDKDocSecurityRsaService/SConscript')
env.SConscript('JavaSDKDocSecuritySRPClient/SConscript')
env.SConscript('JavaSDKDocSecuritySRPService/SConscript')
env.SConscript('JavaSDKDocSignalClient/SConscript')
env.SConscript('JavaSDKDocSignalService/SConscript')
