# Copyright 2011, 2013, Qualcomm Innovation Center, Inc.
# 
#    Licensed under the Apache License, Version 2.0 (the "License");
#    you may not use this file except in compliance with the License.
#    You may obtain a copy of the License at
# 
#        http://www.apache.org/licenses/LICENSE-2.0
# 
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS,
#    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#    See the License for the specific language governing permissions and
#    limitations under the License.
# 

Import('env')

# The return value is the collection of files installed in the build destination.
returnValue = env.SConscript('JavaSDKDocMethodsClient/SConscript', exports = ['env'])
returnValue += env.SConscript('JavaSDKDocMethodsService/SConscript', exports = ['env'])
returnValue += env.SConscript('JavaSDKDocPropertiesClient/SConscript', exports = ['env'])
returnValue += env.SConscript('JavaSDKDocPropertiesService/SConscript', exports = ['env'])
returnValue += env.SConscript('JavaSDKDocSecurityLogonClient/SConscript', exports = ['env'])
returnValue += env.SConscript('JavaSDKDocSecurityLogonService/SConscript', exports = ['env'])
returnValue += env.SConscript('JavaSDKDocSecurityRsaClient/SConscript', exports = ['env'])
returnValue += env.SConscript('JavaSDKDocSecurityRsaClient2/SConscript', exports = ['env'])
returnValue += env.SConscript('JavaSDKDocSecurityRsaService/SConscript', exports = ['env'])
returnValue += env.SConscript('JavaSDKDocSecuritySRPClient/SConscript', exports = ['env'])
returnValue += env.SConscript('JavaSDKDocSecuritySRPService/SConscript', exports = ['env'])
returnValue += env.SConscript('JavaSDKDocSignalClient/SConscript', exports = ['env'])
returnValue += env.SConscript('JavaSDKDocSignalService/SConscript', exports = ['env'])

Return('returnValue')
