# Copyright 2010 - 2012, Qualcomm Innovation Center, Inc.
# 
#    Licensed under the Apache License, Version 2.0 (the "License");
#    you may not use this file except in compliance with the License.
#    You may obtain a copy of the License at
# 
#        http://www.apache.org/licenses/LICENSE-2.0
# 
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS,
#    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#    See the License for the specific language governing permissions and
#    limitations under the License.
# 

import os
import sys
sys.path.append('../../build_core/tools/scons')
from javastatus import JavaStatus
Import('env')

# AllJoyn Java status codes
JavaStatus('org/alljoyn/bus/Status')

# AllJoyn Java binding
#If we are on Linux and Windows
if env['OS'] == 'android':
        # Get P2P java files from core
	#p2p_sources = env.Install('../p2p/org/alljoyn/bus/p2p/service', '../../alljoyn_core/alljoyn_android/alljoyn_android_p2pservice/src/org/alljoyn/bus/p2p/service/P2pHelperService.java')
	#p2p_sources += env.Install('../p2p/org/alljoyn/bus/p2p/service', '../../alljoyn_core/alljoyn_android/alljoyn_android_p2pservice/src/org/alljoyn/bus/p2p/service/P2pManager.java')
	#p2p_sources += env.Install('../p2p/org/alljoyn/bus/p2p/service', '../../alljoyn_core/alljoyn_android/alljoyn_android_p2pservice/src/org/alljoyn/bus/p2p/service/P2pInterface.java')
	#p2p_sources += env.Install('../p2p/org/alljoyn/bus/p2p/service', '../../alljoyn_core/alljoyn_android/alljoyn_android_p2pservice/src/org/alljoyn/bus/p2p/service/P2pReceiver.java')

	main_classes = env.Java('$CLASSDIR', source = ['.'], JAVACLASSPATH=env.subst('$JAVACLASSPATH'))
	p2p_classes = env.Java('$CLASSDIR', source = ['../p2p'], JAVACLASSPATH=env.subst('$JAVACLASSPATH'), JAVAVERSION='1.6')
	proximity_classes = env.Java('$CLASSDIR', source = ['../ice'], JAVACLASSPATH=env.subst('$JAVACLASSPATH'))

	#env.Depends(p2p_classes, p2p_sources)

	alljoyn_jar = env.Jar('$JARDIR/alljoyn.jar', source = [main_classes,p2p_classes,proximity_classes])

if (env['OS'] == 'linux' or env['OS_GROUP'] == 'windows'):
	main_classes = env.Java('$CLASSDIR', source = ['.'], JAVACLASSPATH=env.subst('$JAVACLASSPATH'))
	alljoyn_jar = env.Jar('$JARDIR/alljoyn.jar', source = [main_classes])

if env['VARIANT'] == 'debug' :
    # get a listing of the sources
    env.Jar('$JARDIR/alljoyn-sources.jar', source = ['.','../ice'])
Return('alljoyn_jar')


	
	



